<a href="https://colab.research.google.com/github/it22258380/Deep_learning/blob/main/lab1task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.random.exponential(scale=1,size=(4,4))
print(arr)


[[1.64897305 0.7492738  0.00209324 0.0801063 ]
 [0.80135218 0.35125041 0.06993781 0.29223972]
 [0.4548816  0.57038264 0.40826466 0.17697992]
 [0.43320745 2.05688373 0.25048187 1.03674671]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
